apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: cassandra-service-cip
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra
          ports:
            - containerPort: 9042     
          volumeMounts:
            - name: cassandra-db-disk
              mountPath: /data
      volumes:
        - name: cassandra-db-disk
          persistentVolumeClaim:
            claimName: cassandra-db-disk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-db-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: my-azurefile
