apiVersion: v1
kind: Service
metadata:
  name: cassandra-service-cip
  labels:
    app: cassandra-service-cip
spec:
  type: ClusterIP
  ports:
    - port: 9042
      targetPort: 9042
      protocol: TCP
      name:  CQLNativeTransport
    - port: 7000
      targetPort: 7000
      protocol: TCP
      name:  InternodeCommunication
  selector:
    app: cassandra