apiVersion: apps/v1
kind: Deployment
metadata:
  name: pop-front-deployment
  labels:
    app: pop-front-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pop-front

  template:
    metadata:
      labels:
        app: pop-front
    spec:
      containers:
      - name: frontend
        image: dolphindatabase/visiona-front:0.0.2
        ports:
          - containerPort: 80
