apiVersion: v1
kind: Service
metadata:
  name: pop-deployment-front-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: http
  selector:
    app: pop-deployment