apiVersion: v1
kind: Service
metadata:
  name: back-service-cip
  labels:
    app: back-service-cip
spec:
  type: ClusterIP
  ports:
    - port: 5050
      targetPort: 5050
      protocol: TCP
      name: backend
  selector:
    app: pop-back