apiVersion: apps/v1
kind: Deployment
metadata:
  name: pop-back-deployment
  labels:
    app: pop-back-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pop-back

  template:
    metadata:
      labels:
        app: pop-back
    spec:
      containers:
      - name: backend
        image: dolphindatabase/visiona-back:0.0.2
        ports:
          - containerPort: 5050
        env:
          - name: DATABASE_URL
            value: postgresql://postgres:root@postgis-service-cip:5432/pop
      - name: redis
        image: redis:alpine
        ports:
          - containerPort: 6379
