apiVersion: v1
kind: Service
metadata:
  name: postgis-service-cip
  labels:
    app: postgis-service-cip
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
      name: postgis
  selector:
    app: postgis