apiVersion: v1
kind: Service
metadata:
  name: postgres-headless-svc
spec:
  type: LoadBalancer
  ports:
  - name: postgresql
    port: 5432
    targetPort: 5432
    protocol: TCP 
  selector:
    app: database